In [1]:
import numpy as np

In [3]:
print(np.__version__)

2.4.2


In [7]:
list1 = [1,2,3,4]
list1 = list1 * 2
print(list1)
print(type(list1))

[1, 2, 3, 4, 1, 2, 3, 4]
<class 'list'>


In [13]:
n1 = np.array([1,2,3,4])
n1 = n1 * 2 # also works n1 *=2
print(n1)
print(type(n1))

[2 4 6 8]
<class 'numpy.ndarray'>


In [15]:
n1 = np.array([1,2,3,4])
print(n1)
print(n1.dtype)
print(f"{n1.nbytes} bytes")

[1 2 3 4]
int64
32 bytes


In [16]:
n1 = np.array([1,2,3,4],dtype = np.int32)
print(n1)
print(n1.dtype)
print(f"{n1.nbytes} bytes")

[1 2 3 4]
int32
16 bytes


In [22]:
n1 = np.array([1,2,3,4],dtype = np.float64)
print(n1)
print(n1.dtype)
print(f"{n1.nbytes} bytes")

[1. 2. 3. 4.]
float64
32 bytes


In [25]:
n1 = np.array([1,2,3,4],dtype = np.bool_)
print(n1)
print(n1.dtype)
print(f"{n1.nbytes} bytes")

[ True  True  True  True]
bool
4 bytes


In [26]:
n1 = np.array([1,2,3,4],dtype = np.str_)
print(n1)
print(n1.dtype)
print(f"{n1.nbytes} bytes")

['1' '2' '3' '4']
<U1
16 bytes


In [27]:
n1 = np.array([1000,2000,3000,4000],dtype = np.str_)
print(n1)
print(n1.dtype)
print(f"{n1.nbytes} bytes")

['1000' '2000' '3000' '4000']
<U4
64 bytes


In [29]:
n1 = np.array([1000,2000,3000,4000],dtype = "<U3")
print(n1)
print(n1.dtype)
print(f"{n1.nbytes} bytes")

['100' '200' '300' '400']
<U3
48 bytes


In [31]:
n1 = np.array([1,"string",2,True,3.5,4],dtype = np.object_)
print(n1)
print(n1.dtype)
print(f"{n1.nbytes} bytes")

[1 'string' 2 True 3.5 4]
object
48 bytes


In [33]:
n1 = np.array([1.,2., 3., 4.])

n1 = n1.astype(np.int16)

print(n1)
print(n1.dtype)
print(f"{n1.nbytes} bytes")

[1 2 3 4]
int16
8 bytes
