In [1]:
import numpy as np

In [2]:
array = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(array.shape)

(12,)


In [4]:
array = array.reshape(2,6) # row, column
print(array)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [7]:
array = array.reshape(3,4) 
print(array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [10]:
array = array.reshape(3,-1) # auto column alocation
print(array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [12]:
array = array.reshape(-1,4) # auto row alocation
print(array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [13]:
array = array.reshape(3,2,2) # layer, row, column
print(array)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
