In [1]:
import numpy as np

In [3]:
array = np.array([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12],
                  [13,14,15,16]])

In [4]:
# row selection
print(array[0])

[1 2 3 4]


In [5]:
array[0:3]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [6]:
array[1:4]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [8]:
array[0:4:2]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [9]:
array[::2]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [13]:
# column selection
array[:,0]

array([ 1,  5,  9, 13])

In [14]:
array[:,1]

array([ 2,  6, 10, 14])

In [15]:
array[:,0:3]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

In [16]:
array[:,1:4]

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12],
       [14, 15, 16]])

In [18]:
# row and column slicing
array[0:2,0:2]

array([[1, 2],
       [5, 6]])

In [21]:
array[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

In [22]:
array[0:2,2:4]

array([[3, 4],
       [7, 8]])

In [23]:
array[2:4,1:4]

array([[10, 11, 12],
       [14, 15, 16]])