In [1]:
import numpy as np

In [2]:
# scalar arithmetic
array = np.array([1,2,3])

In [8]:
print(array + 1)
print(array - 2)
print(array * 3)
print(array / 4)
print(array ** 5)

[2 3 4]
[-1  0  1]
[3 6 9]
[0.25 0.5  0.75]
[  1  32 243]


In [9]:
# vectorized math fuction
print(np.sqrt(array))

[1.         1.41421356 1.73205081]


In [15]:
arr = np.array([1.1,2.4,2.6])
print(np.round(arr))

[1. 2. 3.]


In [16]:
print(np.floor(arr))

[1. 2. 2.]


In [17]:
print(np.ceil(arr))

[2. 3. 3.]


In [18]:
print(np.pi)

3.141592653589793


In [20]:
#Exercise
radii = np.array([1,2,3])

In [22]:
# area of a circle
print(np.pi * radii ** 2)

[ 3.14159265 12.56637061 28.27433388]


In [23]:
# element wise arithmetic
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])

In [26]:
print(array1 +array2)
print(array1 - array2)
print(array1 * array2)
print(array1 / array2)
print(array1 ** array2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


In [27]:
# comparison operation
score = np.array([91,55,100,73,82,64])

In [28]:
print(score == 100)

[False False  True False False False]


In [29]:
print(score >= 60)

[ True False  True  True  True  True]


In [30]:
print(score <= 60)

[False  True False False False False]


In [31]:
score[score < 60] = 0
print(score)

[ 91   0 100  73  82  64]
