In [1]:
import numpy as np

In [7]:
array = np.zeros(10)
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [8]:
array = np.zeros((2,3))
print(array)

[[0. 0. 0.]
 [0. 0. 0.]]


In [11]:
array = np.zeros((2,3,10))
print(array)

[[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]]


In [12]:
array = np.ones((2,3,10))
print(array)

[[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]]


In [13]:
array = np.full((2,3,10),5)
print(array)

[[[5 5 5 5 5 5 5 5 5 5]
  [5 5 5 5 5 5 5 5 5 5]
  [5 5 5 5 5 5 5 5 5 5]]

 [[5 5 5 5 5 5 5 5 5 5]
  [5 5 5 5 5 5 5 5 5 5]
  [5 5 5 5 5 5 5 5 5 5]]]


In [20]:
array = np.eye(3)
print(array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [21]:
array = np.empty((2,3))
print(array)

[[ 1.79769313e+308 -1.79769313e+308  2.00000000e+000]
 [ 2.22044605e-016  2.22507386e-308  4.94065646e-324]]


In [25]:
array = np.arange(1,10,2) # start stop step
print(array)

[1 3 5 7 9]


In [26]:
array = np.arange(1,10,2.5)
print(array)

[1.  3.5 6.  8.5]


In [28]:
array = np.linspace(1,10,4) # start stop num
print(array)

[ 1.  4.  7. 10.]


In [29]:
array = np.linspace(1,10,6) # start stop num
print(array)

[ 1.   2.8  4.6  6.4  8.2 10. ]
