In [1]:
import numpy as np

In [2]:
ages = np.array([[21,17,19,20,16,30,18,65],
                 [39,22,15,99,18,19,20,21]])

In [6]:
teenagers = ages[ages < 18]
print(teenagers)

[17 16 15]


In [10]:
adults = ages[(ages >= 18) & (ages < 65)]
print(adults)

[21 19 20 30 18 39 22 18 19 20 21]


In [12]:
seniors = ages[ages >= 65]
print(seniors)

[65 99]


In [14]:
evens = ages[ages % 2 == 0]
print(evens)

[20 16 30 18 22 18 20]


In [15]:
odds = ages[ages % 2 != 0]
print(odds)

[21 17 19 65 39 15 99 19 21]


In [17]:
adults = np.where(ages >= 18, ages, -1)
print(adults)

[[21 -1 19 20 -1 30 18 65]
 [39 22 -1 99 18 19 20 21]]
