In [1]:
import numpy as np

In [2]:
rng = np.random.default_rng()

In [30]:
print(rng.integers(low= 1, high= 7))

21


In [31]:
print(rng.integers(low= 1, high= 101))

57


In [32]:
print(rng.integers(low= 1, high= 7, size= 3))

[2 6 5]


In [33]:
print(rng.integers(low= 1, high= 7, size= (3,2)))

[[2 4]
 [1 6]
 [5 6]]


In [37]:
rng = np.random.default_rng(seed = 1)
print(rng.integers(low= 1, high= 7, size= (3,2)))

[[3 4]
 [5 6]
 [1 1]]


In [41]:
# Floating point numbers
print(np.random.uniform(low= -1, high= 1))

0.4246044924378878


In [42]:
print(np.random.uniform(low= -1, high= 1,size= 3))

[0.8529274  0.1001278  0.11406803]


In [43]:
print(np.random.uniform(low= -1, high= 1,size= (3,2)))

[[ 0.3691639  -0.47004403]
 [-0.83925109 -0.61455396]
 [ 0.23536843  0.40113102]]


In [47]:
# shuffle
rng = np.random.default_rng()
array = np.array([1,2,3,4,5])
rng.shuffle(array)
print(array)

[1 2 3 4 5]


In [74]:
# random choice
rng = np.random.default_rng()
fruits = np.array(["🍇","🍉","🍎","🥭","🍍"])
fruit = rng.choice(fruits)
print(fruit)

🍇


In [75]:
fruits = rng.choice(fruits,size = 3)
print(fruits)

['🥭' '🍎' '🍍']


In [76]:
fruits = rng.choice(fruits,size = (3,3))
print(fruits)

[['🥭' '🥭' '🍎']
 ['🍍' '🍍' '🍎']
 ['🥭' '🍎' '🍎']]
