In [1]:
import numpy as np

In [2]:
array = np.array([[1,2,3],[4,5,6]])

In [3]:
np.save("data", array)
print("Numpy file was saved")

Numpy file was saved


In [4]:
#load file
arr = np.load("data.npy")
print("file loaded successfully")

file loaded successfully


In [5]:
print(arr)

[[1 2 3]
 [4 5 6]]


In [6]:
# save multiply arrays
array1 = np.array([[1,2,3],[4,5,6]])
array2 = np.array([1.6,2.3,3.1,4.1])

In [7]:
np.savez("datas", array1, array2)
print("saved")

saved


In [8]:
np.savez_compressed("compressed", array1, array2)
print("saved")

saved


In [9]:
# load multiple arrays
arrays = np.load("datas.npz")

In [10]:
print(arrays)

NpzFile 'datas.npz' with keys: arr_0, arr_1


In [12]:
array1 = arrays["arr_0"]
array2 = arrays["arr_1"]

In [13]:
print(array1)
print(array2)

[[1 2 3]
 [4 5 6]]
[1.6 2.3 3.1 4.1]
